# Generated by Django 2.2.6 on 2019-11-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191104_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='img/noimage/noimage.jpg', upload_to='img/'),
        ),
    ]
