# Generated by Django 2.2.6 on 2019-11-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191104_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='img/noimage/noimage.jpg', null=True, upload_to='img/'),
        ),
    ]
