# Generated by Django 2.2.6 on 2019-11-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191104_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='img/noimage/noimage.jpg', null=True, upload_to='media/'),
        ),
    ]
