# Generated by Django 2.2.6 on 2019-11-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20191105_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, default='noimage.jpg', null=True, upload_to='c_img/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='noimage.jpg', null=True, upload_to='img/'),
        ),
    ]
