# Generated by Django 2.2.6 on 2019-11-06 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20191105_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='data published'),
        ),
    ]
